<?php
echo '<html xmlns="http://www.w3.org/1999/xhtml" lang="en">';
echo '';
echo '<head>';
echo '<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
echo '';
echo '<title>Mehdi Quantom</title>';
echo '';
echo '<style type="text/css">';
echo '';
echo '';
echo 'body {';
echo 'margin: 0;  padding: 0;  margin-bottom: 45px;  margin-top: 8px;';
echo 'background: #77b;';
echo '}';
echo 'body, td {';
echo 'font: 16px "Trebuchet MS", Verdana, Arial, Helvetica, sans-serif;';
echo '}';
echo '';
echo '#subTitle {';
echo 'background: #000;  color: #fff;  padding: 9px;  font-weight: bold;';
echo '}';
echo '';
echo '#siteNavigation a, #siteNavigation .current {';
echo 'font-weight: bold;  color: #648;';
echo '}';
echo '#siteNavigation a:link    { text-decoration: none; }';
echo '#siteNavigation a:visited { text-decoration: none; }';
echo '';
echo '#siteNavigation .current { background-color: #cdd; }';
echo '';
echo '#siteNavigation a:hover   { text-decoration: none;  background-color: #fdf;  color: #0f0; }';
echo '#siteNavigation a:active  { text-decoration: none;  background-color: #ccc; }';
echo '';
echo '';
echo 'a:link    { text-decoration: underline;  color: #800; }';
echo 'a:visited { text-decoration: underline;  color: #000; }';
echo 'a:hover   { text-decoration: underline;  color: #c00; }';
echo 'a:active  { text-decoration: underline; }';
echo '';
echo '#pageContent {';
echo 'clear: both;';
echo 'border-bottom: 5px solid #000;';
echo 'padding: 10px;  padding-top: 20px;';
echo 'line-height: .65em;';
echo 'background-image: url(gif.gif);';
echo 'background-repeat: no-repeat;';
echo 'background-position: bottom right;';
echo '}';
echo '';
echo '#pageContent, #siteNavigation {';
echo 'background-color: #880;';
echo '}';
echo '';
echo '';
echo '.imgLeft  { float: left;   margin-right: 10px;  margin-bottom: 10px; }';
echo '.imgRight { float: right;  margin-left: 10px;   margin-bottom: 10px; }';
echo '';
echo 'hr { height: 1px;  color: #448;  background-color: #448;  margin-bottom: 10px; }';
echo '';
echo 'h1 { margin: 0;  font-weight: bold;  font-size: 2em; }';
echo 'h2 { margin: 0;  font-weight: bold;  font-size: 1.6em; }';
echo 'h3 { margin: 0;  font-weight: bold;  font-size: 1.3em; }';
echo 'h4 { margin: 0;  font-weight: bold;  font-size: 1.18em; }';
echo '';
echo '.blak { background-color: #000; }';
echo '.hide { display: none; }';
echo '.tableWidth { min-width: 800px; }';
echo '';
echo '.tblRegular       { border-collapse: collapse; }';
echo '.tblRegular td    { padding: 6px;  background-image: url(fade.gif);  border: 2px solid #99c; }';
echo '.tblHeaderColor, .tblHeaderColor td { background: #99c; }';
echo '.tblNoBorder td   { border: 0; }';
echo '';
echo '';
echo '';
echo '</style>';
echo '';
echo '</head>';
echo '';
echo '<body>';
echo '<table width="76%" border="0" align="center" cellspacing="0" cellpadding="3" class="tableWidth">';
echo '<tr>';
echo '<td id="subTitle">Mehdi Quantom - Movie Archive</td>';
echo '</tr>';
echo '</table>';
echo '<table width="76%" border="0" align="center" cellspacing="0" cellpadding="0" class="tableWidth">';
echo '<tr class="blak">';
echo '<td>';
echo '<table width="100%" border="0" align="center" cellspacing="5" cellpadding="0">';
echo '<tr>';
echo '<td colspan="6">';
echo '<table width="100%" border="0" align="center" cellspacing="0" cellpadding="10">';
echo '<tr>';
echo '<td id="pageContent">';
echo '';
echo '';
echo '<h2 ALIGN=Center>Index Of Latest Uploads:</H2>';
echo '<table border="0" width="100%" cellspacing="25" cellpadding="0">';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">Better Nate Than Ever (2022) [720p] [WEBRip] - 2022-04-02 04:24</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">Death On The Nile 2022 - 2022-03-30 02:39</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">Jackass Forever (2022) [720p] [WEBRip] - 2022-03-25 23:48</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">Dog 2022 - 2022-03-18 23:38</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">Spider-Man No Way Home 2021 - 2022-03-18 23:34</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">All Of My Heart Inn Love 2017 - 2022-03-18 23:34</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">All Of My Heart The Wedding 2018 - 2022-03-18 23:33</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">Deep Water (2022) [720p] [WEBRip] - 2022-03-18 12:54</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">All Of My Heart 2015 - 2022-03-17 08:40</A>';
echo '</TD>';
echo '</TR>';
echo '<TR>';
echo '<TD BACKGROUND="fade.gif">';
echo '&middot; <A HREF="Generating.html">The Adam Project 2022 - 2022-03-17 08:39</A>';
echo '</TD>';
echo '</TR>';
echo '';
echo '</TABLE>';
echo '<BR>';
echo '<H6 ALIGN="left">';
echo '<I>Quantom Services [2022]</I>';
echo '</H6>';
echo '';
echo '';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '</td>';
echo '</tr>';
echo '</table>';
echo '';
echo '<table width="76%" border="0" align="center" valign="bottom" cellspacing="0" cellpadding="0">';
echo '<tr>';
echo '<td id="footer"><small>&copy; Mehdi Quantom</small></td>';
echo '</tr>';
echo '</table>';
echo '';
echo '</body>';
echo '';
echo '</html>';
echo '';
echo '';
echo '';
?>